### ISSUE TITLE
RecipientFilter instances are never deleted

### ISSUE THREAD

**Issue by jsza** [Source-Python-Dev-Team/Source.Python#124]
I've managed to reproduce a memory leak on TF2 Linux (SP version 327) with:

``` python
from listeners import OnTick
from messages import KeyHintText
from filters.players import PlayerIter

text = 'a' * 240

@OnTick
def on_tick():
    for player in PlayerIter():
        for x in range(40):
            KeyHintText(text).send(player.index)
```

The flood of data causes the game client to freeze, but running the plugin causes a steady increase of ~1MB memory usage every few seconds.

I've tested with SayText2 and HintText messages with the same result.

**Comment by Ayuto** [comment]
This memory leak is caused by the RecipientFilter instances, which are never deleted. This is caused by the HeldType definition:
https://github.com/Source-Python-Dev-Team/Source.Python/blob/79593cbf43dfd444d9484c5daaa355e5d82ef8ea/src/core/modules/filters/filters_recipients_wrap.cpp#L84

Funny thing:
If I correct the HeldType, the server crashes as soon as the RecipientFilter instance gets deleted. Delaying the delete doesn't help. If the instance gets deleted e.g. 5 seconds after the user message has been sent, the server crashes exactly after the 5 seconds passed.

I will need more time to figure out what's happening here...

**Comment by Ayuto** [comment]
Finally, I found the reason for the crashes! It's the memory debugging include here:
https://github.com/alliedmodders/hl2sdk/blob/css/public/tier1/utlmemory.h#L22

This affects us, because we are using CUtlVector for our MRecipientFilter class and the CUtlVector class utilizes CUtlMemory. I will now try to find out why the memory debugging causes crashes.

**Comment by jsza** [comment]
Thank you for looking into this Ayuto!

Has there been any more progress on getting the fix to compile?

**Comment by Ayuto** [comment]
No, sorry. IRC, I ran into other issues, when I fixed the errors.

**Comment by invincibleqc** [comment]
While this doesn't fix the real issue, https://github.com/Source-Python-Dev-Team/Source.Python/commit/82393fb07bd3e9ef304c9afc171e810e158063bf prevent leaking from the effects and messages package.
