### ISSUE TITLE
Linux: @HookUserMessage('SayText2') crashes server

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#334]
Hello,

@HookUserMessage('SayText2') crashes on linux when a player is on the server.

```
sp info

IMPORTANT: Please copy the full output.

Checksum      : 0f23eb6e30e633b9a028c12552cb6f25
Date          : 2020-05-13 16:11:47.263541
OS            : Linux-5.4.0-26-generic-x86_64-with-debian-bullseye-sid
Game          : css
SP version    : 695
Github commit : 92b3adfaaaf1bb9ecd2be1ddad55bc68589b4152
Server plugins:
   00: Source.Python, (C) 2012-2019, Source.Python Team.
SP plugins:
   00: test
```

test.py
```
from messages.hooks import HookUserMessage

@HookUserMessage('SayText2')
def on_user_message(recipients, data):
    print(data)
```

Console log:
```
Client "Frag" connected (XXXXXXXXX).
Server waking up from hibernation
Segmentation fault (core dumped)
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Wed 13 May 2020 06:13:55 PM CEST: Server restart in 10 seconds
```

**Comment by Frag1337** [comment]
Any update?

**Comment by Ayuto** [comment]
Not yet, sorry! I didn't have time to take a look at it.

**Comment by Ayuto** [comment]
Just tested it with the latest SP version (699) and was unable to reproduce it. Could you please check if it was "accidentally" fixed in a later version?
```
Game will not start until both teams have players.
{'index': 1, 'chat': 1, 'message': 'Cstrike_Chat_All', 'param1': 'Ayuto', 'param2': 'asd', 'param3': '', 'param4': ''}
Ayuto: asd

sp info

IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : a204c8959008c3305614a7de6b86db68
Date          : 2020-08-15 18:11:54.027363
OS            : Linux-4.4.0-144-generic-i686-with-debian-jessie-sid
Game          : css
SP version    : 699
Github commit : 7e06ce8e445e17425dfcecdad5895473c294fabc
Server plugins:
   00: Source.Python, (C) 2012-2020, Source.Python Team.
SP plugins:
   00: test
--------------------------------------------------------
```

**Comment by Frag1337** [comment]
Hey @Ayuto 

Sorry, I sadly had no linux server to test it again.

But I've installed a fresh css gameserver now on Ubuntu 20.04 and still get the following crash.

```
sp info
IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : dbb83a6b3babcbd41a7d427173062fde
Date          : 2020-12-14 19:01:46.533442
OS            : Linux-5.4.0-58-generic-x86_64-with-debian-bullseye-sid
Game          : css
SP version    : 702
Github commit : 99ed4dca7b439f5fc4ade054355767b23af497df
Server plugins:
   00: Source.Python, (C) 2012-2020, Source.Python Team.
SP plugins:
--------------------------------------------------------

sp plugin load test
[SP] Loading plugin 'test'...
[SP] Successfully loaded plugin 'test'.
Client "Frag" connected (***CENSORED***).
Server waking up from hibernation
Core hook (run_command) has been initialized.
Segmentation fault (core dumped)
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Mon Dec 14 19:01:59 UTC 2020: Server restart in 10 seconds
```
I can load the plugin fine, but joining or being already on the server results in a immediate crash.

**Comment by Frag1337** [comment]
I dont know if it makes any difference, but to load Source.Python I had to do this fix here:

https://forums.sourcepython.com/viewtopic.php?p=13976#p13976 Method #2

**Comment by Frag1337** [comment]
I've reinstalled 2x VMs on my Windows 10 PC with Debian and Ubuntu and both crashed when using this snippet.

```
sp info

IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : 7c33b61780e0f33c1175b39accca96a2
Date          : 2020-12-17 17:45:40.739352
OS            : Linux-5.4.0-58-generic-x86_64-with-debian-bullseye-sid
Game          : css
SP version    : 702
Github commit : 99ed4dca7b439f5fc4ade054355767b23af497df
Server plugins:
   00: Source.Python, (C) 2012-2020, Source.Python Team.
SP plugins:
--------------------------------------------------------
```

Tried with `-debug`:
```
sp plugin load test
[SP] Loading plugin 'test'...
[SP] Successfully loaded plugin 'test'.
bot_add
Core hook (run_command) has been initialized.
Segmentation fault (core dumped)
cat: hlds.809733.pid: No such file or directory
email debug.log to linux@valvesoftware.com
Thu Dec 17 17:45:57 UTC 2020: Server restart in 10 seconds
```

Debian didnt require a workaround for libffi6, but resulted in the same crash.

It doesnt even have to be a real player to crash. Loading plugin works fine - crashes the moment when the bot joins with `bot_add`.

My debug.log is empty..
`----------------------------------------------
CRASH: Thu Dec 17 17:45:57 UTC 2020
Start Line: ./srcds_linux -game cstrike -strictportbind -ip XX.XX.XX.XX -port 27015 +clientport 27005 +tv_port 27020 +map surf_skyworld_tricks -maxplayers 32 -tickrate 100 -insecure -debug
End of Source crash report
----------------------------------------------
`

**Comment by Frag1337** [comment]
I tried to dig more and installed a csgo server on the same machine where css crashes.

But with success! It loads on `CS:GO` without a crash.

```
sp info

IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : 4bf794ea8496019da428b925cbc0b468
Date          : 2020-12-17 18:10:24.928280
OS            : Linux-5.4.0-58-generic-x86_64-with-debian-bullseye-sid
Game          : csgo
SP version    : 702
Github commit : 99ed4dca7b439f5fc4ade054355767b23af497df
Server plugins:
   00: Source.Python, (C) 2012-2020, Source.Python Team.
SP plugins:
--------------------------------------------------------
```

```
sp plugin load test
[SP] Loading plugin 'test'...
[SP] Successfully loaded plugin 'test'.
bot_add
L 12/17/2020 - 18:10:31: "Henry<3><BOT><>" connected, address ""
L 12/17/2020 - 18:10:31: "Henry<3><BOT>" switched from team <Unassigned> to <TERRORIST>
L 12/17/2020 - 18:10:31: "Henry<3><BOT><>" entered the game
```

Sorry for the frequent replies, I'm just trying to gather all informations for you.
