### ISSUE TITLE
Linux: @PreHook(Entity(0).set_transmit) crashes server

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#335]
```
sp info

IMPORTANT: Please copy the full output.

Checksum      : cf426f5381fcc412cd39635f0e1c7bd5
Date          : 2020-05-13 16:52:30.573888
OS            : Linux-5.4.0-26-generic-x86_64-with-debian-bullseye-sid
Game          : css
SP version    : 695
Github commit : 92b3adfaaaf1bb9ecd2be1ddad55bc68589b4152
Server plugins:
   00: Source.Python, (C) 2012-2019, Source.Python Team.
SP plugins:
```

test.py
```
from entities.entity import Entity
from memory.hooks import PreHook

@PreHook(Entity(0).set_transmit)
def pre_set_transmit(args):
    print('HELLO')
```

console log
```
[SP] Loading plugin 'test'...
[SP] Successfully loaded plugin 'test'.
HELLO
HELLO
HELLO
```

SERVER FREEZES

```
Could not find steamerrorreporter binary. Any minidumps will be uploaded in-processWatchDog! Server took too long to process (probably infinite loop).
Host_Error: WatchdogHandler called - server exiting.


Segmentation fault (core dumped)
Add "-debug" to the ./srcds_run command line to generate a debug.log to help with solving this problem
Wed 13 May 2020 06:51:50 PM CEST: Server restart in 10 seconds
```

**Comment by Frag1337** [comment]
Any update?

**Comment by Ayuto** [comment]
Not yet, sorry! I didn't have time to take a look at it.

**Comment by jordanbriere** [comment]
Did you update to 696? DynamicHooks was updated in that version, maybe it is related to the issues that were fixed in that build.

**Comment by Frag1337** [comment]
@jordanbriere It sadly didnt help. I've updated and still crashes.

**Comment by Ayuto** [comment]
I'm also unable to reproduce this crash. Could you please re-test to verify it hasn't been fixed already?

**Comment by Frag1337** [comment]
@Ayuto @jordanbriere 

Sorry for the late response.

I sadly had no linux server to test again.

But I've reinstalled a Ubuntu 20.04 css gameserver and it looks like the issue has been fixxed. I dont get any crash from it. Thanks.
